
export const amenitiesOptions = [
  "Heated",
  "Loungers", 
  "Towels Provided",
  "Food Available",
  "Changing Rooms",
  "Hot Tub/Jacuzzi",
  "Sauna",
  "WiFi",
  "Bar Service",
  "Parking",
  "Accessible",
  "Child Friendly",
  "City Views",
  "Thames Views",
  "Countryside Views",
  "Spa",
  "Steam Room",
  "Hydrotherapy",
  "Fitness Center",
  "Business Center",
  "Historic Property",
  "Luxury Service",
  "Private Cabanas",
  "Champagne Service",
  "Michelin Star Restaurant",
  "Golf Course",
  "Country Estate",
  "Rooftop Views",
  "24/7 Access",
  "Boutique Design"
];
