
export const amenitiesOptions = [
  "Heated",
  "Loungers", 
  "Towels Provided",
  "Food Available",
  "Changing Rooms",
  "Hot Tub/Jacuzzi",
  "Sauna",
  "WiFi",
  "Bar Service",
  "Parking",
  "Accessible",
  "Child Friendly",
  "City Views",
  "Sea Views",
  "Mountain Views",
  "Spa",
  "Steam Room",
  "Hydrotherapy",
  "Fitness Center",
  "Business Center",
  "Beach Access",
  "Garden Setting",
  "Historic Property",
  "Luxury Service",
  "Infinity Pool",
  "Private Cabanas",
  "Champagne Service",
  "Michelin Star Restaurant",
  "Wildlife Views",
  "Northern Lights"
];
